### ISSUE TITLE
Search box unfocused when switching between keyboard layouts (languages) in Firefox on GNOME

### ISSUE THREAD

**Issue by igor-kobzev** [duckduckgo/BrowserServicesKit#121]
I'm sorry if I'm opening this issue in the wrong place. I'm just not exactly sure where I should, since you have so many repos.

On GNOME on Linux in Firefox if I switch keyboard layout with the Super+Space key combo while on the duckduckgo.com website and with the search box in focus, the search box becomes unfocused and I can't continue typing in it until I manually click on it to bring it back in focus. Please refer this annoying bug to the correct repo if this is the wrong place for it.

**Comment by brindy** [comment]
Hi, sorry for the very long delay in replying.  If you're still experiencing this issue the best place is to report it is via the send feedback button on the bottom right of our results page. https://duckduckgo.com/?q=feedback

Thanks for being part of the duck side!
