### ISSUE TITLE
Compile error: Variable used within its own initial value

### ISSUE THREAD

**Issue by kjayathilake** [duckduckgo/BrowserServicesKit#22]
Found a small issue with BrowserServiceKit 7.1.4 version
`Suggestions > SuggesionProcessing.swift : Line 64`

<img width="894" alt="Screenshot 2021-09-30 at 18 52 15" src="https://user-images.githubusercontent.com/3039881/135463594-3f5ff52f-8d3f-4708-a51f-4af6a465935a.png">

I would like to fix the issue and start contributing.

**Comment by brindy** [comment]
Hello, please ensure you're using the latest Xcode.  That's only a problem on older versions of Swift. 

I'm afraid we aren't taking contributions for this project right now as we are still iterating at speed while we build our macOS browser. 

Thanks for your interest!
