### ISSUE TITLE
Duckduckgo browser crashed on Windows 10 x64

### ISSUE THREAD

**Issue by JuraLys** [duckduckgo/BrowserServicesKit#624]
See attached events from Windows log
[DuckDuckGo-crash-event.zip](https://github.com/duckduckgo/BrowserServicesKit/files/13927243/DuckDuckGo-crash-event.zip)

**Comment by JuraLys** [comment]
one more crash, see 
![duckgo-crash(](https://github.com/duckduckgo/BrowserServicesKit/assets/146434286/f02c8cdf-7369-4b86-9943-a6f258da5c19)
[DuckDuckGo-crash-event2.zip](https://github.com/duckduckgo/BrowserServicesKit/files/13930579/DuckDuckGo-crash-event2.zip)

**Comment by brindy** [comment]
Hi - I will pass this on to the Windows team, but this repo is for Apple related code.  Thanks for using DuckDuckGo!
