### ISSUE TITLE
Please add WebExtensions to support keepass plugins for Chrome

### ISSUE THREAD

**Issue by vkuznet** [duckduckgo/BrowserServicesKit#646]
Hi, I'm not sure if it is proper repository, therefore feel free to close it and redirect me to proper channel. I posted a ticket on KeePassXC repo  about a possibility to support KeePassXC in DuckDuckGo browser. They replied, see  https://github.com/keepassxreboot/keepassxc/issues/10249#issuecomment-1918058626, that it will be possible if browser will support WebExtensions to use chrome store. Said that, I think it is a browser feature and I wonder if it is possible for DuckDockGo browser. I understand that it has its own password manager but for lots of people who used cross platform managers like KeePass it would be useful to use it directly in DuckDuckGo browser.

**Comment by brindy** [comment]
Hi, thanks for using DuckDuckGo.  We are continuously looking at this stuff (extensions and supporting more password managers), so rest assured it's on our radar. 

Technically speaking Chrome extensions are not supported by WebKit at this team, but Apple are adding extension support for [MV3](https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3). Once it's available we'll be evaluating how best to make this available to our users.

Thanks for your patience!
